In [3]:
# import dependencies
import pandas as pd
import glob

In [4]:
#set path

path = r'C:\Users\getso\OneDrive\Documents\Assignments\Tableau-Challenge\citibike_data'

# make a join string of the CSVs using glob
all_files = glob.glob(path + "/*.csv")

li = []

# read them into a list 
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

# concatenate
frame = pd.concat(li, axis=0, ignore_index=True)

In [9]:
# Concatenate all data into one DataFrame
combined_df = pd.concat(li, ignore_index=True)

In [10]:
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137962,395,2020-05-31 23:35:50.9460,2020-05-31 23:42:26.5300,3202,Newport PATH,40.727224,-74.033759,3276,Marin Light Rail,40.714584,-74.042817,42250,Subscriber,1992,1
137963,1681,2020-05-31 23:38:30.8240,2020-06-01 00:06:32.0360,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42396,Customer,1997,1
137964,1657,2020-05-31 23:39:07.2680,2020-06-01 00:06:44.5740,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42331,Customer,1987,1
137965,420,2020-05-31 23:45:28.3290,2020-05-31 23:52:28.3680,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,40517,Subscriber,1999,1
137966,87,2020-05-31 23:50:55.8390,2020-05-31 23:52:23.0920,3272,Jersey & 3rd,40.723332,-74.045953,3211,Newark Ave,40.721525,-74.046305,42314,Subscriber,1976,1